export default {
  login: "Jas3429",
  id: 101297751,
  node_id: "U_kgDOBgmuVw",
  avatar_url: "https://avatars.githubusercontent.com/u/101297751?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Jas3429",
  html_url: "https://github.com/Jas3429",
  followers_url: "https://api.github.com/users/Jas3429/followers",
  following_url: "https://api.github.com/users/Jas3429/following{/other_user}",
  gists_url: "https://api.github.com/users/Jas3429/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Jas3429/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Jas3429/subscriptions",
  organizations_url: "https://api.github.com/users/Jas3429/orgs",
  repos_url: "https://api.github.com/users/Jas3429/repos",
  events_url: "https://api.github.com/users/Jas3429/events{/privacy}",
  received_events_url: "https://api.github.com/users/Jas3429/received_events",
  type: "User",
  site_admin: false,
  name: "Jason Sheriff",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Student of Back and Front End Development",
  twitter_username: null,
  public_repos: 5,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2022-03-09T23:11:06Z",
  updated_at: "2023-05-27T10:53:38Z",
};
